services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    expose:
      - '4200'
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-customer-service:
    image: stanthikun802/backend-customer-service:docker
    ports:
      - 5000:5000
    expose:
      - 5000

  # backend-payment-service:
  #   image: stanthikun802/backend-payment-service:latest
  #   ports:
  #     - 3101:8080
  #   expose:
  #     - 3101

  # backend-product-service:
  #   image: stanthikun802/backend-product-service:latest
  #   ports:
  #     - 3102:8081
  #   expose:
  #     - 3102

  # backend-report-service:
  #   image: stanthikun802/backend-report-service:latest
  #   ports:
  #     - 3103:8082
  #   expose:
  #     - 3103

volumes:
  my-datavolume: