services:
  server:
    build:
      context: .
      args:
        progress: plain
        NODE_ENV: docker
    environment:
      NODE_ENV: docker
    ports:
      - 8080:80
    expose:
      - '80'
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-customer-service:
    image: stanthikun802/backend-customer-service:docker
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    expose:
      - 5000

  backend-payment-service:
    image: stanthikun802/backend-payment-service:docker
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3101:8080
    expose:
      - 8080

  backend-product-service:
    image: stanthikun802/backend-product-service:docker
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3102:8081
    expose:
      - 8081

  backend-report-service:
    image: stanthikun802/backend-report-service:docker
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3103:8082
    expose:
      - 8082
